---
networks:
  nginx_net:
    name: nginx_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.118.100.0/24"
          gateway: "10.118.100.1"

services:
  traefik:
    image: ghcr.io/traefik/traefik:v3.6.7
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_net
    volumes:
      # - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /docker/traefik/${SERVER}/letsencrypt:/etc/traefik/acme
      - /docker/traefik/${SERVER}/logs:/opt/logs
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      - CLOUDFLARE_ZONE_API_TOKEN=${CLOUDFLARE_ZONE_API_TOKEN}
      - LETS_ENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
    command:
      # access log
      - --accesslog=true
      - --accesslog.filepath=/opt/logs/access.log
      - --log.filePath=/opt/logs/traefik.log
      # Enable dashboard
      - --api.dashboard=true
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=tcp://socket-proxy:2375 # Enable for Socket Proxy. Disable otherwise.
      - --providers.docker.network=nginx_net 
      # Skip internal cert check
      - --serversTransport.insecureSkipVerify=true
      # Set up LetsEncrypt
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${LETS_ENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Set up an insecure listener that redirects all traffic to TLS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      # Set up the TLS configuration for our websecure listener
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}
      # needed so internal DNS doesn't dick with things
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
    labels:
      # Dashboard config
      - traefik.enable=true
      - traefik.http.routers.traefik-dash.rule=Host(`${SERVER}.${DOMAIN}`)
      - traefik.http.routers.traefik-dash.entrypoints=websecure
      - traefik.http.routers.traefik-dash.service=api@internal
      - traefik.http.routers.traefik-dash.tls.certResolver=letsencrypt
      - traefik.http.routers.traefik-dash.middlewares=mw_compress,mw_headers,mw_xff
      - traefik.http.middlewares.mw_xff.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.mw_compress.compress=true
      - traefik.http.middlewares.mw_headers.headers.browserXssFilter=true
      - traefik.http.middlewares.mw_headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.mw_headers.headers.frameDeny=true
      - traefik.http.middlewares.mw_headers.headers.referrerPolicy=no-referrer-when-downgrade
      - traefik.http.middlewares.mw_headers.headers.stsSeconds=31536000

# Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:3.2.11
    container_name: traefik-socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      - nginx_net
    privileged: true # true for VM. False (default) for unprivileged LXC container.
    # ports:
      #- "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    read_only: true
    tmpfs:
      - /run
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=warning # debug,info,notice,warning,err,crit,alert,emerg
      ## Container actions
      - ALLOW_START=0 # Portainer
      - ALLOW_STOP=0 # Portainer
      - ALLOW_RESTARTS=0 # Portainer
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=0 # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=0 # Portainer
      - INFO=0 # Portainer
      - NETWORKS=0 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=0 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0 # Portainer
      - VOLUMES=0 # Portainer
      - DISABLE_IPV6=1 #optional
